name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login docker
        run: docker login -u nazatmustag -p Agent4747#
      - name: Build docker
        run: docker build -t nazatmustag/practice .
      - name: Publish docker
        run: docker push nazatmustag/practice:latest
  deploy:
    needs:  build
    runs-on: [self-hosted]
    steps:
      - name: Pull image
        run: docker pull nazatmustag/practice:latest
      - name: Delete old container
        run: docker rm -f nazatmustag-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name nazatmustag-container nazatmustag/practice
        