name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker
        run: docker build -t ecommerce/nazatmustag .
      - name: Publish docker
        run: docker push ecommerce/nazatmustag:latest
  deploy:
    needs:  build
    runs-on: [aws-ecommerce]
    steps:
      - name: Pull image
        run: docker pull ecommerce/nazatmustag:latest
      - name: Delete old container
        run: docker rm -f nazatmustag-container
      - name: Run docker container
        run: docker -d -p 3000:3000 -name nazatmustag-container ecommerce/nazatmustag
        